version: '3.8'

services:
  cui-tools:
    build: .
    container_name: cui-tools
    volumes:
      - .:/workspace
      - ./cookies.txt:/workspace/cookies.txt
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: ["tail", "-f", "/dev/null"]
